name: test_for_max
description: "flutter project for max"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  get_it: ^7.7.0
  flutter_svg: ^2.0.10+1
  http: ^1.2.2
  retrofit: ^4.2.0
  dio: ^5.6.0
  json_annotation: ^4.9.0
  retrofit_generator: ^8.2.0
  logger: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  json_serializable: ^6.8.0

flutter:

  uses-material-design: true